### ISSUE TITLE
Missing commas 

### ISSUE THREAD

**Issue by MIDAV0** [FLock-io/client-interface#25]
https://github.com/FLock-io/client-interface/blob/02c34117ee5fbd4f758a1676b73034ecc99f36f8/src/renderer/hooks/useTaskData.ts#L217

**Comment by sjhddh** [comment]
thank you vadzim! could you work on this?

**Comment by MIDAV0** [comment]
This one has been fixed in v0.0.5 by @rodrigopavezi
