### ISSUE TITLE
client interface needs to upgraded to new versions of our visual identity

### ISSUE THREAD

**Issue by sjhddh** [FLock-io/client-interface#31]

**Comment by sjhddh** [comment]
our design guide: https://github.com/FLock-io/design-guide

Our logo intro video: https://www.youtube.com/watch?v=fgrWQuwkzOM

Please update our client accordingly

**Comment by sjhddh** [comment]
And Logo Packs here:

[Icon Shape.zip](https://github.com/FLock-io/client-interface/files/12507888/Icon.Shape.zip)

**Comment by abebeos** [comment]
- https://github.com/bountysource/core/issues/1586

**Comment by Proryanator** [comment]
Hey there! Looking at working on this issue for you.

Can you give more details on what part of the client you want updated? Based on the links it could be anything from just the logo or intro video, to the entire app being overhauled to new icons, fonts, logos, etc. (this should help define the scope of this issue).

**Comment by ghost** [comment]
@sjhddh , why deletion? "FLock-io deleted a comment from abebeos"

Your funds are in danger:

* https://app.bountysource.com/issues/123844785-client-interface-needs-to-upgraded-to-new-versions-of-our-visual-identity
* https://github.com/bountysource/core/issues/1586

**Comment by sjhddh** [comment]
hey @Proryanator just the client app icon and the intro video when the app is opened.

**Comment by Proryanator** [comment]
@sjhddh I can fix the .gif to actually play but, do you want an actual video to play with sound for the splash screen? :)

**Comment by Proryanator** [comment]
@sjhddh when you get a chance I opened a PR for this. In the PR there's some notes on what was changed. Let me know if you have any questions!

**Comment by sjhddh** [comment]
thx! will review soooooon

**Comment by sjhddh** [comment]
Amazing! Thank you @Proryanator it's now all merged!

**Comment by Proryanator** [comment]
@sjhddh you're welcome! Glad I could help. I went ahead and claimed the bounty too 😸

**Comment by sjhddh** [comment]
yep, sweet. and I have it approved. Also, please feel free to checkout our repo and raise any issues you may find. we are happy to convert some of them into bounties for communities to help build! @Proryanator

**Comment by ghost** [comment]
> we are happy to convert some of them into bounties for communities to help build!

Please review https://github.com/bountysource/core/issues/1586 before posting any new bounties on bountysource.
