### ISSUE TITLE
"share"button does not work when in training v 0.0.5

### ISSUE THREAD

**Issue by sjhddh** [FLock-io/client-interface#39]
<img width="1422" alt="Screenshot 2023-09-06 at 21 02 07" src="https://github.com/FLock-io/client-interface/assets/5778228/d6bbc3a5-62d2-4166-aec9-4d4d78a3b09d">

**Comment by MIDAV0** [comment]
Added:
When user click share, box pops up where user can either visit link directly or click on copy icon to copy link to clipboard
![image](https://github.com/FLock-io/client-interface/assets/79284856/e73b86c6-09c0-49d6-aa68-d2f103706a4d)

When copy icon clicked notification pops up
![image](https://github.com/FLock-io/client-interface/assets/79284856/611af891-b10f-483a-8458-b69bb1f43838)

Link leads to flock website https://testnet.flock.io/train where it will automatically open tasks page and open specified task for user
